# Change these first
owner: omarifs # Your GitHub organization or username, where this repository lives
repo: uptime-monitoring # The name of this repository
user-agent: omarifs

sites:
  - name: Agrowisata Amanah
    url: https://agrowisataamanah.id
  - name: Berkah Multi
    url: https://berkahmulti.com
  - name: AdGuard Websolusi
    url: https://dns.websolusi.com
  - name: Flask Websolusi
    url: https://flask.websolusi.com
    method: "GET"
    headers:
    - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Omarifs"
  - name: Gama Aims Backend
    url: https://gamaaims.com
  - name: Jaya Samudra Agency
    url: https://jayasamudra-agency.com
  - name: KB TK Taman Bahagia
    url: https://kbtktamanbahagia.sch.id
    method: "GET"
    headers:
    - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Omarifs"
  - name: Tools Websolusi
    url: https://tools.websolusi.com
  - name: Websolusi
    url: https://websolusi.com
    method: "GET"
    headers:
    - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Omarifs"
  - name: Monit Server (Lessie)
    url: https://live.websolusi.com
  - name: VPS Arif 
    url: 103.161.184.136
    check: "tcp-ping"
  - name: Resolver (17.82)
    url: 103.123.17.82
    port: 53
    check: "tcp-ping"
  - name: VPN 16-118 
    url: 103.123.16.118
    port: 53
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.websolusi.com
  #baseUrl: /uptime-monitoring
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svghttps://i.dnva.me/91501668368a2bc-pngaaa.com-4965957.png
  logoUrl: https://i.dnva.me/91501668368a2bc-pngaaa.com-4965957.png
  name: Uptime Websolusi
  introTitle: "**Uptime Monitoring** is the open-source uptime monitor and status page"
  introMessage: This is a status page which uses **real-time** data
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
